mdp:
  nacos:
    ip: '@config.nacos.ip@'
    port: '@config.nacos.port@'
    namespace: '@config.nacos.namespace@'
    username: '@config.nacos.username@'
    password: '@config.nacos.password@'

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      password: 'SbtyMveYNfLzTks7H0apCmyStPzWJqjy'
      database: 6
  datasource:
    druid:
      username: 'root'
      driverClassName: com.mysql.cj.jdbc.Driver
      password: 'ZHadmin123.'
      url: jdbc:mysql://127.0.0.1:3218/mdp?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true


logging:
  file:
    path: /data_mdp/logs


dubbo:
  registry:
    # 使用nacos注册中心
    address: nacos://${mdp.nacos.username}:${mdp.nacos.password}@${mdp.nacos.ip}:${mdp.nacos.port}?namespace=${mdp.nacos.namespace}