spring:
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      password: 'SbtyMveYNfLzTks7H0apCmyStPzWJqjy'
      database: 6
  datasource:
    druid:
      username: 'root'
      driverClassName: com.mysql.cj.jdbc.Driver
      password: 'root'
      url: jdbc:mysql://127.0.0.1:3306/mdp?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true


dromara:
  x-file-storage:
    default-platform: minio
    minio:
      - platform: minio
        domain: https://static.tangyh.top/
        endPoint: https://static.tangyh.top
        enableStorage: true
        bucket-name: dev
        access-key: vgOHpkYcJ6iloQmaVFLp
        secret-key: EKJOpRET306cIiCoOAcp1tWh5Ij30oTlqqPEiwSM

dubbo:
  registry:
    # 使用本地 zookeeper（启动 ZookeeperRegistryServer 即可）
    address: zookeeper://localhost:2181