mdp:
  nacos:
    ip: '@config.nacos.ip@'
    port: '@config.nacos.port@'
    namespace: '@config.nacos.namespace@'
    username: '@config.nacos.username@'
    password: '@config.nacos.password@'

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      password: 'SbtyMveYNfLzTks7H0apCmyStPzWJqjy'
      database: 6
  datasource:
    druid:
      username: 'root'
      driverClassName: com.mysql.cj.jdbc.Driver
      password: 'ZHadmin123.'
      url: jdbc:mysql://127.0.0.1:3218/mdp?serverTimezone=Asia/Shanghai&characterEncoding=utf8&usemdpcode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true

# Sa-Token配置
sa-token:
  sso-client:
    # sso-server 端主机地址
    server-url: http://workbench.mddata.top/api/workbench
    # 单点登录服务
    authUrl: 'http://workbench.mddata.top/#/auth/login'
    # API 接口调用秘钥
    secret-key: SSO-C3-kQwIOrYvnXmSDkwEiFngrKidMcdrg123

logging:
  file:
    path: /data_mdp/logs

dromara:
  x-file-storage: #文件存储配置
    local-plus:
      - platform: localPlus
        domain: http://open.mddata.top/preview/ # 访问域名
        base-path: local-plus/ # 基础路径
        path-patterns: /preview/** # 访问路径
        storage-path: /data_mdp/upload-file/
        enableStorage: true
        enableAccess: true

dubbo:
  registry:
    # 使用nacos注册中心
    address: nacos://${mdp.nacos.username}:${mdp.nacos.password}@${mdp.nacos.ip}:${mdp.nacos.port}?namespace=${mdp.nacos.namespace}