spring:
  data:
    redis:
      host: 127.0.0.1
      port: 16379
      password: 'SbtyMveYNfLzTks7H0apCmyStPzWJqjy'
      database: 6
  datasource:
    druid:
      username: 'root'
      driverClassName: com.mysql.cj.jdbc.Driver
      password: 'root'
      url: jdbc:mysql://127.0.0.1:3306/mdp?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true

# Sa-Token配置
sa-token:
  sso-client:
    # sso-server 端主机地址
    server-url: http://sso.mddata.top/api/workbench
    # 单点登录服务
    authUrl: 'http://sso.mddata.top/workbench/#/auth/login'
    # API 接口调用秘钥
    secret-key: SSO-C3-kQwIOrYvnXmSDkwEiFngrKidMcdrg123

logging:
  file:
    path: /data_prod/mdp/logs